recordcount=1
operationcount=100000
threadcount=128
fieldcount=10
fieldlength=256
insertproportion=1
readproportion=0
updateproportion=0
scanproportion=0
readallfields=true
dotransactions=false
requestdistribution=uniform

tikv.type=raw
tikv.pd=127.0.0.1:2379
tikv.conncount=128
tikv.batchsize=128
