#!/usr/bin/env bash
# Export env vars for continuum-bench native Scylla runs.
set -euo pipefail
PROFILE="${1:-scylla-1}"
case "$PROFILE" in
  scylla-1)
    export CONTINUUM_BENCH_SCYLLA_CONTACT_POINTS="${CONTINUUM_BENCH_SCYLLA_CONTACT_POINTS:-127.0.0.1:9042}"
    ;;
  scylla-3)
    export CONTINUUM_BENCH_SCYLLA_CONTACT_POINTS="${CONTINUUM_BENCH_SCYLLA_CONTACT_POINTS:-127.0.0.1:9042,127.0.0.1:9043,127.0.0.1:9044}"
    ;;
  *)
    echo "unknown profile: $PROFILE (use scylla-1 or scylla-3)" >&2
    exit 1
    ;;
esac
export CONTINUUM_BENCH_SCYLLA_KEYSPACE="${CONTINUUM_BENCH_SCYLLA_KEYSPACE:-continuum}"
export CONTINUUM_TEST_SCYLLA_CONTACT_POINTS="${CONTINUUM_TEST_SCYLLA_CONTACT_POINTS:-$CONTINUUM_BENCH_SCYLLA_CONTACT_POINTS}"
export CONTINUUM_TEST_SCYLLA_KEYSPACE="${CONTINUUM_TEST_SCYLLA_KEYSPACE:-continuum_test}"
echo "CONTINUUM_BENCH_SCYLLA_CONTACT_POINTS=$CONTINUUM_BENCH_SCYLLA_CONTACT_POINTS"
echo "CONTINUUM_BENCH_SCYLLA_KEYSPACE=$CONTINUUM_BENCH_SCYLLA_KEYSPACE"
