#!/usr/bin/env bash
# Export env vars for continuum-bench raw TiKV runs.
set -euo pipefail
export CONTINUUM_BENCH_TIKV_PD_ENDPOINT="${CONTINUUM_BENCH_TIKV_PD_ENDPOINT:-127.0.0.1:2379}"
export CONTINUUM_TEST_TIKV_PD_ENDPOINT="${CONTINUUM_TEST_TIKV_PD_ENDPOINT:-$CONTINUUM_BENCH_TIKV_PD_ENDPOINT}"
echo "CONTINUUM_BENCH_TIKV_PD_ENDPOINT=$CONTINUUM_BENCH_TIKV_PD_ENDPOINT"
